[package]
name = "gtk-rs-msvc"
version = "0.1.0"
authors = ["kykc"]
build = "build.rs"

[dependencies]
gio = "0.8"

[target.'cfg(windows)'.build-dependencies]
vcpkg = "0.2.6"

[dependencies.gtk]
version = "0.8"
features = ["v3_20"]
