[package]
name = "gtk-rs-msvc"
version = "0.1.0"
authors = ["kykc"]
build = "build.rs"

[dependencies.gtk]
version = "0.8.1"
features = ["v3_20"]

[dependencies.gio]
version = ""

[target.'cfg(windows)'.build-dependencies]
vcpkg = "0.2.6"
